FROM node:18-alpine

WORKDIR /app

# Copier les fichiers de dépendances
COPY package*.json ./

# Installer les dépendances
RUN npm install

# Copier le reste du code
COPY . .

# Exposer le port frontend
EXPOSE 3000

# Démarrer le serveur de développement React
CMD ["npm", "start"]
